// Generates supabase/seed.sql from shared/demoCatalog.js.   Usage: node scripts/generate-seed.mjs
import { writeFileSync } from 'node:fs';
import { DEMO_CATEGORIES, DEMO_PRODUCTS, demoProductRow } from '../shared/demoCatalog.js';

const q = (v) => (v == null ? 'null' : `'${String(v).replaceAll("'", "''")}'`);
const lines = [];
lines.push('-- ⚠️ DEMO DATA ONLY. Generated by scripts/generate-seed.mjs from shared/demoCatalog.js.');
lines.push('-- Run AFTER schema.sql. All products are flagged is_demo = true so you can remove them');
lines.push('-- from Admin → Products → "Remove demo products" (or: delete from products where is_demo).');
lines.push('');
lines.push('insert into public.categories (name, slug, sort_order) values');
lines.push(DEMO_CATEGORIES.map((c, i) => `  (${q(c.name)}, ${q(c.slug)}, ${i + 1})`).join(',\n'));
lines.push('on conflict (slug) do nothing;\n');
for (const raw of DEMO_PRODUCTS) {
  const p = demoProductRow(raw);
  lines.push(
    `insert into public.products (slug, name, brand, category_id, short_description, description, ingredients, storage_info, authenticity_info, price, comparison_price, show_comparison, cost_price, stock, weight, country_of_origin, expiry_info, is_featured, is_active, is_demo)\n` +
      `select ${q(p.slug)}, ${q(p.name)}, ${q(p.brand)}, (select id from public.categories where slug = ${q(p.category)}), ${q(p.short_description)}, ${q(p.description)}, ${q(p.ingredients)}, ${q(p.storage_info)}, ${q(p.authenticity_info)}, ${p.price}, ${p.comparison_price ?? 'null'}, ${p.show_comparison}, ${p.cost_price}, ${p.stock}, ${q(p.weight)}, ${q(p.country_of_origin)}, ${q(p.expiry_info)}, ${p.featured}, true, true\n` +
      `where not exists (select 1 from public.products where slug = ${q(p.slug)});\n`,
  );
}
writeFileSync(new URL('../supabase/seed.sql', import.meta.url), lines.join('\n'));
console.log('supabase/seed.sql written');
